version: '3.8'
services:
  db:
    container_name: mock-reset-db
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mockreset
      MARIADB_DATABASE: mockreset
      MARIADB_USER: mockreset
      MARIADB_PASSWORD: mockreset
    ports:
      - '3306:3306'